[phases.setup]
nixPkgs = ['python312', 'pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn factory_project.wsgi --log-file -'
